INSERT INTO RULE (id, name, max_Pins, max_Frames, max_Rolls_Per_Frame, strike_Bonus, strike_After_Pins, spare_Bonus, spare_After_Pins) VALUES (1, 'Classic Bowling', 10, 10, 2, 10, 2, 10, 1);
INSERT INTO RULE (id, name, max_Pins, max_Frames, max_Rolls_Per_Frame, strike_Bonus, strike_After_Pins, spare_Bonus, spare_After_Pins) VALUES (2, 'African Version', 15, 5, 3, 15, 2, 15, 3);

-- negative ID so no problem with the autogenerated sequence ID
INSERT INTO USER_PLAYER (id, username, password) VALUES (-1, 'test', '$2a$12$K4CuOyl7AP0VDWfBN8mevexQq/NVTwdWgQrcBvAbMyCr.zVm0hq8i');  -- password: test
INSERT INTO USER_PLAYER (id, username, password) VALUES (-2, 'test2', '$2a$12$/prBWlgv1wOoBjw76WX7euoG2a8sX/.dNWIpbG8aVVDzuhQ4KeOV2'); -- password: test2
INSERT INTO USER_PLAYER (id, username, password) VALUES (-3, 'test3', '$2a$12$JwEEhFBCaL0DPFwqPGWn1.4pwcH.PmJ6sB4A2PwqbpcVCcDiPIVTa'); -- password: test3


INSERT INTO GAME (id, name, rule_id) VALUES (-1, 'Classic', 1);
INSERT INTO GAME (id, name, rule_id) VALUES (-2, 'Ancient', 2);

INSERT INTO GAME_PLAYERS (GAME_ID, PLAYER_ID) VALUES (-2, -2);
INSERT INTO GAME_PLAYERS (GAME_ID, PLAYER_ID) VALUES (-2, -3);

INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-1, 1, ARRAY[8, 1, 1], 10, -2, -2);
INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-2, 2, ARRAY[8, 7, 0], 28, -2, -2);
INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-3, 3, ARRAY[1, 2, 1], 31, -2, -2);
INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-4, 4, ARRAY[15, 0, 0], 50, -2, -2);
INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-5, 5, ARRAY[1, 2, 1], 53, -2, -2);

INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-6, 1, ARRAY[15, 0, 0], 26, -2, -3);
INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-7, 2, ARRAY[8, 1, 2], 37, -2, -3);
INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-8, 3, ARRAY[1, 2, 12], 62, -2, -3);
INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-9, 4, ARRAY[6, 4, 1], 73, -2, -3);
INSERT INTO FRAME (ID, FRAME_NUMBER, ROLLS, TOTAL_SCORE, GAME_ID, PLAYER_ID) VALUES (-10, 5, ARRAY[15, 8, 2, 3], 101, -2, -3);

   



